# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-03 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(max_length=4096, verbose_name='Описание')),
                ('picture', models.ImageField(upload_to='film_pics/', verbose_name='Постер')),
            ],
        ),
    ]
